language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: true
node_js:
  - 'stable'
# Configure Travis with Firefox
# stopped working: http://karma-runner.github.io/0.13/plus/travis.html
# fixed in: https://stackoverflow.com/a/57517901/1614973
services:
  - xvfb
script: karma start karma.conf.js --single-run --browsers Firefox
before_script:
  - export DISPLAY=:99.0
  # - sh -e /etc/init.d/xvfb start
