language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: true
node_js:
  - 'stable'
  - '4'
  - '6'
# Configure Travis with Firefox
# http://karma-runner.github.io/0.13/plus/travis.html
script: karma start karma.conf.js --single-run --browsers Firefox
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
